### ISSUE TITLE
feat: Add search bar to search by name

### ISSUE THREAD

**Issue by ShinichiShi** [Alitindrawan24/nuxt-pokedex#12]
Hey @Alitindrawan24 , i would like to contribute to this project by 

- adding a search bar to search a pokemon by its name

*HOW THIS HELPS?* 

1. users can learn about more details about their specific pokemon by searching its name

Kindly assign me this issue under the hacktoberfest tag, so that i can raise my PR soon!

**Comment by Alitindrawan24** [comment]
There was a search bar before but I just realized that the search bar is gone probably because of the previous merged PR. I will assign this issue to you. Thank you @ShinichiShi
