### ISSUE TITLE
[STYLE] Add border radius to button Next/Previous for consistency

### ISSUE THREAD

**Issue by rhnas110** [Alitindrawan24/nuxt-pokedex#14]
## Description
The button for handle pagination need rounded for consistency.
![image](https://github.com/user-attachments/assets/862bb0ed-ded6-426b-a3b1-e9a50fe1dcfb)

## To Reproduce
![image](https://github.com/user-attachments/assets/0834d116-b96a-4978-b6ec-e4bf5fa3ffbc)
1. I add a radius of the same size as the others

## Additional context
Sir @Alitindrawan24  can you assign this issue to me Sir? I am new to open source contributions and I would love to contribute to your project Sir. I also participated in Hacktoberfest2024.

**Comment by Alitindrawan24** [comment]
Already assigned @rhnas110
