### ISSUE TITLE
Feat: Light Mode to the Pokedex 

### ISSUE THREAD

**Issue by ShinichiShi** [Alitindrawan24/nuxt-pokedex#17]
Hey @Alitindrawan24 , i would like to add light mode into this...with a combo of blue and red combination.

Kindly assign this to me, so that i can immediately raise my PR !

**Comment by ShinichiShi** [comment]
CC: @Alitindrawan24

**Comment by Alitindrawan24** [comment]
Okay @ShinichiShi already assigned

**Comment by ShinichiShi** [comment]
Hey @Alitindrawan24, kindly merge the attached PR before hacktoberfest pls :)
