### ISSUE TITLE
 Add Height and Weight Data to Each Pokémon Entry in the Pokedex

### ISSUE THREAD

**Issue by frankgomezdev** [Alitindrawan24/nuxt-pokedex#7]
I'd like to request that height and weight be added to the Pokémon entries in the Pokedex. These are key features that are currently missing. It would improve accuracy and provide users with a more complete experience that aligns with the Pokedex we see in-game & series. 

Please feel free to assign this issue to me.

**Comment by Alitindrawan24** [comment]
Already assigned @frankgomezdev
